"""
Olfactory Data Module - Efficient Data Loading with PyTorch Lightning

Copyright (c) 2025 Tom White
Licensed under the MIT License

🚫 STUDENTS: DO NOT EDIT THIS FILE
To change data settings, edit configs/data/your_dataset.yaml

This module handles all data loading, preprocessing, and batching.
Optimized for speed with:
- Parallel data loading
- Memory-mapped arrays for large datasets
- Persistent workers
- Automatic GPU transfer optimization
"""

import torch
import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional, Tuple
from torch.utils.data import DataLoader, TensorDataset, random_split
import pytorch_lightning as pl
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from omegaconf import DictConfig


class OlfactoryDataModule(pl.LightningDataModule):
    """
    Data module for olfactory prediction datasets.
    
    Handles:
    - Loading CSV data
    - Train/val/test splitting
    - Creating DataLoaders with optimizations
    - Data validation
    """
    
    def __init__(self, config: DictConfig):
        super().__init__()
        self.config = config
        
        # Data will be loaded in setup()
        self.train_dataset = None
        self.val_dataset = None
        self.test_dataset = None
        
        # Scaler for features (if needed)
        self.scaler = None
        
        # Store data info for model
        self.input_dim = None
        self.output_dim = None
        
    def prepare_data(self):
        """
        Download or prepare data (runs once on a single process).
        
        Use this for downloading or writing to disk.
        We don't need this for local CSV files.
        """
        pass
    
    def setup(self, stage: Optional[str] = None):
        """
        Load and split data (runs on every process).
        
        Args:
            stage: 'fit', 'validate', 'test', or 'predict'
        """
        # Check if using brain PCA target mode
        target_type = self.config.data.get('target_type', None)
        
        if target_type == 'brain_pca':
            # Load molecular features and brain PCA targets separately
            X, y = self._load_brain_pca_data()
        else:
            # Standard single CSV loading
            data_path = Path(self.config.data.data_path)
            
            if not data_path.exists():
                raise FileNotFoundError(
                    f"Data file not found: {data_path}\n"
                    f"Please place your data file at this location or update the path in your config."
                )
            
            print(f"\n📂 Loading data from: {data_path}")
            df = pd.read_csv(data_path)
            print(f"✅ Loaded {len(df)} samples with {len(df.columns)} columns")
            
            # Validate data
            self._validate_data(df)
            
            # Extract features and target
            X, y = self._prepare_features_target(df)
        
        # Store dimensions for model
        self.input_dim = X.shape[1]
        self.output_dim = y.shape[1] if len(y.shape) > 1 else 1
        
        # Update config with dimensions (for model building)
        # Allow adding new keys to config
        from omegaconf import OmegaConf
        OmegaConf.set_struct(self.config, False)
        self.config.data.input_dim = self.input_dim
        self.config.data.output_dim = self.output_dim
        OmegaConf.set_struct(self.config, True)
        
        print(f"📊 Features: {self.input_dim}, Target: {self.output_dim}")
        
        # Split data
        split_config = self.config.data.train_test_split
        test_size = split_config.get('test_size', 0.2)
        random_state = split_config.get('random_state', 42)
        shuffle = split_config.get('shuffle', True)
        
        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=test_size,
            random_state=random_state,
            shuffle=shuffle
        )
        
        # Further split train into train/val (80/20 of training set)
        X_train, X_val, y_train, y_val = train_test_split(
            X_train, y_train,
            test_size=0.2,
            random_state=random_state,
            shuffle=shuffle
        )
        
        print(f"📦 Split: Train={len(X_train)}, Val={len(X_val)}, Test={len(X_test)}")
        
        # Convert to PyTorch tensors
        X_train = torch.FloatTensor(X_train)
        X_val = torch.FloatTensor(X_val)
        X_test = torch.FloatTensor(X_test)
        y_train = torch.FloatTensor(y_train).reshape(-1, self.output_dim)
        y_val = torch.FloatTensor(y_val).reshape(-1, self.output_dim)
        y_test = torch.FloatTensor(y_test).reshape(-1, self.output_dim)
        
        # Create datasets
        self.train_dataset = TensorDataset(X_train, y_train)
        self.val_dataset = TensorDataset(X_val, y_val)
        self.test_dataset = TensorDataset(X_test, y_test)
        
        print("✅ Data setup complete!\n")
    
    def _load_brain_pca_data(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Load molecular features and brain PCA targets using prepare_training_data().
        
        Returns:
            X: Molecular features [n_molecules, n_features]
            y: Brain PCA scores [n_molecules, n_pca_components]
        """
        from ..stages.preprocessing import prepare_training_data
        
        # Load molecular features
        mol_features_path = Path(self.config.data.data_path)
        if not mol_features_path.exists():
            raise FileNotFoundError(f"Molecular features not found: {mol_features_path}")
        
        print(f"\n📂 Loading molecular features from: {mol_features_path}")
        mol_df = pd.read_csv(mol_features_path, index_col=0)
        
        # Load brain PCA targets
        brain_pca_path = Path(self.config.data.brain_pca_path)
        if not brain_pca_path.exists():
            raise FileNotFoundError(f"Brain PCA scores not found: {brain_pca_path}")
        
        print(f"📂 Loading brain PCA targets from: {brain_pca_path}")
        
        # Use prepare_training_data to align X and y
        print(f"🔗 Aligning molecular features with brain PCA targets...")
        X, y, common_cids, metadata = prepare_training_data(
            molecular_features_df=mol_df,
            brain_pca_scores_path=str(brain_pca_path),
            cid_column=self.config.data.get('cid_column', 'CID')
        )
        
        print(f"✅ Data aligned successfully!")
        print(f"   Molecules: {len(common_cids)}")
        print(f"   Features (X): {X.shape}")
        print(f"   Targets (y): {y.shape}")
        
        # Optional: Check for issues
        if self.config.data.get('check_nan', True):
            if np.isnan(X).any() or np.isnan(y).any():
                raise ValueError("NaN values detected in aligned data!")
        
        if self.config.data.get('check_inf', True):
            if np.isinf(X).any() or np.isinf(y).any():
                raise ValueError("Infinite values detected in aligned data!")
        
        return X, y
    
    def _validate_data(self, df: pd.DataFrame):
        """Validate that data meets requirements"""
        # Support single or multiple target columns
        target_cols_cfg = self.config.data.get('target_columns', None)
        target_col = self.config.data.get('target_column', None)
        if target_cols_cfg is not None and isinstance(target_cols_cfg, (list, tuple)) and len(target_cols_cfg) > 0:
            target_cols = list(target_cols_cfg)
        elif target_col is not None:
            target_cols = [target_col]
        else:
            raise ValueError("No target column(s) specified. Set `data.target_column` or `data.target_columns` in config.")
        
        # Check target columns exist
        missing_targets = [c for c in target_cols if c not in df.columns]
        if missing_targets:
            raise ValueError(
                f"Target column(s) not found: {missing_targets}.\n"
                f"Available columns: {list(df.columns)}"
            )
        
        # Check for missing values
        missing = df.isnull().sum()
        if missing.any():
            missing_cols = missing[missing > 0]
            print(f"⚠️  Warning: Missing values found:")
            for col, count in missing_cols.items():
                pct = (count / len(df)) * 100
                print(f"  {col}: {count} ({pct:.1f}%)")
            
            # Handle missing values
            strategy = self.config.data.get('missing_values', {}).get('strategy', 'drop_rows')
            if strategy == 'drop_rows':
                df.dropna(inplace=True)
                print(f"  Dropped rows with missing values. Remaining: {len(df)}")
        
        # Check for infinite values
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        if np.isinf(df[numeric_cols]).any().any():
            print("⚠️  Warning: Infinite values found in data. Replacing with NaN...")
            df.replace([np.inf, -np.inf], np.nan, inplace=True)
            df.dropna(inplace=True)
    
    def _prepare_features_target(self, df: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray]:
        """
        Extract features and target from dataframe.
        
        Returns:
            X: Feature array [n_samples, n_features]
            y: Target array [n_samples] or [n_samples, n_targets]
        """
        # Determine target columns (single or multi)
        # Try reading targets from config; if absent, auto-detect common PC columns in the dataframe
        target_cols_cfg = None
        target_col_single = None
        try:
            target_cols_cfg = self.config.data.get('target_columns', None)
            target_col_single = self.config.data.get('target_column', None)
        except Exception:
            # In case DictConfig get isn't available due to struct constraints
            target_cols_cfg = self.config.data.target_columns if 'target_columns' in self.config.data else None
            target_col_single = self.config.data.target_column if 'target_column' in self.config.data else None
        # Precedence: if target_columns is provided and non-empty, ignore target_column
        if isinstance(target_cols_cfg, (list, tuple)) and len(target_cols_cfg) > 0:
            target_cols = list(target_cols_cfg)
        elif isinstance(target_cols_cfg, list) and len(target_cols_cfg) == 0:
            # explicit empty list means use single target if provided
            target_cols = [target_col_single] if target_col_single is not None else []
        elif target_cols_cfg is None and target_col_single is not None:
            target_cols = [target_col_single]
        else:
            # Fallback: auto-detect PCA target columns if present in data
            candidate_targets = [c for c in ['PC1','PC2','PC3','PC4','PC5'] if c in df.columns]
            if candidate_targets:
                target_cols = candidate_targets
            else:
                raise ValueError("No target column(s) specified. Set `data.target_column` or `data.target_columns` in config, and ensure target columns exist in the CSV.")
        
        # Columns to exclude
        exclude_cols = list(target_cols)
        if self.config.data.get('smiles_column'):
            exclude_cols.append(self.config.data.smiles_column)
        if self.config.data.get('exclude_columns'):
            exclude_cols.extend(self.config.data.exclude_columns)
        
        # Get feature columns
        feature_cols = self.config.data.get('feature_columns', None)
        if feature_cols is None:
            # Use all numeric columns except excluded
            all_numeric = df.select_dtypes(include=[np.number]).columns
            feature_cols = [col for col in all_numeric if col not in exclude_cols]
        
        # Extract features and targets
        print(f"🔧 Using target columns: {target_cols}")
        X = df[feature_cols].values.astype(np.float32)
        if len(target_cols) == 1:
            y = df[target_cols[0]].values.astype(np.float32)
        else:
            y = df[target_cols].values.astype(np.float32)
        
        return X, y
    
    def train_dataloader(self) -> DataLoader:
        """
        Create training dataloader with optimizations.
        
        Optimizations:
        - num_workers: Parallel data loading
        - pin_memory: Faster GPU transfer
        - persistent_workers: Reuse workers between epochs
        - shuffle: Randomize order each epoch
        """
        return DataLoader(
            self.train_dataset,
            batch_size=self.config.data.get('batch_size', 32),
            shuffle=True,
            num_workers=self.config.data.get('num_workers', 4),
            pin_memory=self.config.data.get('pin_memory', True),
            persistent_workers=True if self.config.data.get('num_workers', 4) > 0 else False,
            drop_last=False
        )
    
    def val_dataloader(self) -> DataLoader:
        """Create validation dataloader"""
        return DataLoader(
            self.val_dataset,
            batch_size=self.config.data.get('batch_size', 32),
            shuffle=False,
            num_workers=self.config.data.get('num_workers', 4),
            pin_memory=self.config.data.get('pin_memory', True),
            persistent_workers=True if self.config.data.get('num_workers', 4) > 0 else False,
            drop_last=False
        )
    
    def test_dataloader(self) -> DataLoader:
        """Create test dataloader"""
        return DataLoader(
            self.test_dataset,
            batch_size=self.config.data.get('batch_size', 32),
            shuffle=False,
            num_workers=self.config.data.get('num_workers', 4),
            pin_memory=self.config.data.get('pin_memory', True),
            persistent_workers=True if self.config.data.get('num_workers', 4) > 0 else False,
            drop_last=False
        )
    
    def get_data_info(self) -> dict:
        """Get information about the dataset"""
        return {
            'input_dim': self.input_dim,
            'output_dim': self.output_dim,
            'train_size': len(self.train_dataset) if self.train_dataset else 0,
            'val_size': len(self.val_dataset) if self.val_dataset else 0,
            'test_size': len(self.test_dataset) if self.test_dataset else 0,
        }
