"""
Cache Manager - Intelligent caching for pipeline stages

Copyright (c) 2025 Tom White
Licensed under the MIT License

🚫 STUDENTS: DO NOT EDIT THIS FILE
Caching is automatic based on your config settings.

This module provides smart caching that:
- Saves processing time (5-10 min per run!)
- Automatically detects when to recompute
- Manages disk space
- Provides cache inspection and cleanup

Cache invalidation (when cache is recomputed):
- Feature extraction: SMILES column, descriptor settings change
- Preprocessing: PCA settings, scaling method changes
- Training: Model architecture, training params change (but reuses preprocessed data)
"""

import pickle
import json
import hashlib
from pathlib import Path
from typing import Any, Optional, Dict
from datetime import datetime
import shutil
from omegaconf import DictConfig, OmegaConf


class CacheManager:
    """
    Manages caching for expensive pipeline stages.
    
    Uses content-based hashing: cache is invalidated only when
    the relevant config parameters change.
    """
    
    def __init__(self, cache_root: Path, config: DictConfig):
        """
        Args:
            cache_root: Base directory for all caches
            config: Full experiment configuration
        """
        self.cache_root = Path(cache_root)
        self.config = config
        
        # Create cache directories
        self.features_cache = self.cache_root / "features"
        self.preprocessing_cache = self.cache_root / "preprocessing"
        self.models_cache = self.cache_root / "models"
        
        for cache_dir in [self.features_cache, self.preprocessing_cache, self.models_cache]:
            cache_dir.mkdir(parents=True, exist_ok=True)
    
    def get_cache_key(self, stage: str, config_subset: Optional[DictConfig] = None) -> str:
        """
        Generate a cache key based on relevant config parameters.
        
        Args:
            stage: Pipeline stage ('features', 'preprocessing', 'training')
            config_subset: Specific config to hash (if None, uses stage-relevant config)
        
        Returns:
            Unique cache key (hash of relevant config)
        """
        if config_subset is None:
            config_subset = self._get_stage_config(stage)
        
        # Convert config to string for hashing
        config_str = OmegaConf.to_yaml(config_subset)
        
        # Create hash
        hash_obj = hashlib.md5(config_str.encode('utf-8'))
        cache_key = hash_obj.hexdigest()[:16]  # Use first 16 chars
        
        return cache_key
    
    def _get_stage_config(self, stage: str) -> DictConfig:
        """Extract the config parameters relevant to each stage"""
        if stage == 'features':
            # Features depend on: data source, feature extraction params
            return OmegaConf.create({
                'data_path': self.config.data.data_path,
                'smiles_column': self.config.data.get('smiles_column', None),
                'feature_columns': self.config.data.get('feature_columns', None),
            })
        
        elif stage == 'preprocessing':
            # Preprocessing depends on: feature config + preprocessing params
            return OmegaConf.create({
                'features': self._get_stage_config('features'),
                'preprocessing': self.config.preprocessing,
            })
        
        elif stage == 'training':
            # Training depends on: preprocessing config + model + training params
            return OmegaConf.create({
                'preprocessing': self._get_stage_config('preprocessing'),
                'model': self.config.model,
                'training': self.config.training,
            })
        
        else:
            raise ValueError(f"Unknown stage: {stage}")
    
    def cache_exists(self, stage: str, cache_key: Optional[str] = None) -> bool:
        """Check if valid cache exists for this stage"""
        if cache_key is None:
            cache_key = self.get_cache_key(stage)
        
        cache_file = self._get_cache_path(stage, cache_key)
        metadata_file = cache_file.with_suffix('.json')
        
        return cache_file.exists() and metadata_file.exists()
    
    def load_cache(self, stage: str, cache_key: Optional[str] = None) -> Any:
        """
        Load cached data for a stage.
        
        Returns:
            Cached data if exists, None otherwise
        """
        if cache_key is None:
            cache_key = self.get_cache_key(stage)
        
        if not self.cache_exists(stage, cache_key):
            return None
        
        cache_file = self._get_cache_path(stage, cache_key)
        
        print(f"📦 Loading cached {stage} (key: {cache_key})")
        
        with open(cache_file, 'rb') as f:
            data = pickle.load(f)
        
        # Update last accessed time
        self._update_metadata(stage, cache_key, access_only=True)
        
        print(f"✅ Cache loaded successfully!")
        return data
    
    def save_cache(self, stage: str, data: Any, cache_key: Optional[str] = None):
        """
        Save data to cache.
        
        Args:
            stage: Pipeline stage
            data: Data to cache (must be picklable)
            cache_key: Optional custom cache key
        """
        if cache_key is None:
            cache_key = self.get_cache_key(stage)
        
        cache_file = self._get_cache_path(stage, cache_key)
        
        print(f"💾 Saving {stage} cache (key: {cache_key})")
        
        # Save data
        with open(cache_file, 'wb') as f:
            pickle.dump(data, f, protocol=pickle.HIGHEST_PROTOCOL)
        
        # Save metadata
        self._update_metadata(stage, cache_key, access_only=False)
        
        # Get file size
        size_mb = cache_file.stat().st_size / (1024 * 1024)
        print(f"✅ Cache saved ({size_mb:.2f} MB)")
    
    def _get_cache_path(self, stage: str, cache_key: str) -> Path:
        """Get the file path for a cache key"""
        if stage == 'features':
            return self.features_cache / f"{cache_key}.pkl"
        elif stage == 'preprocessing':
            return self.preprocessing_cache / f"{cache_key}.pkl"
        elif stage == 'training':
            return self.models_cache / f"{cache_key}.pkl"
        else:
            raise ValueError(f"Unknown stage: {stage}")
    
    def _update_metadata(self, stage: str, cache_key: str, access_only: bool = False):
        """Update or create metadata file for cache"""
        cache_file = self._get_cache_path(stage, cache_key)
        metadata_file = cache_file.with_suffix('.json')
        
        now = datetime.now().isoformat()
        
        if access_only and metadata_file.exists():
            # Just update last accessed
            with open(metadata_file, 'r') as f:
                metadata = json.load(f)
            metadata['last_accessed'] = now
        else:
            # Create new metadata
            config_subset = self._get_stage_config(stage)
            metadata = {
                'stage': stage,
                'cache_key': cache_key,
                'created': now,
                'last_accessed': now,
                'config': OmegaConf.to_container(config_subset),
                'file_size_bytes': cache_file.stat().st_size if cache_file.exists() else 0,
            }
        
        with open(metadata_file, 'w') as f:
            json.dump(metadata, f, indent=2)
    
    def list_caches(self, stage: Optional[str] = None) -> Dict[str, list]:
        """
        List all cached items.
        
        Args:
            stage: If specified, only list caches for this stage
        
        Returns:
            Dictionary mapping stage to list of cache info dicts
        """
        stages = [stage] if stage else ['features', 'preprocessing', 'training']
        
        cache_info = {}
        
        for s in stages:
            cache_dir = self._get_cache_dir(s)
            caches = []
            
            for metadata_file in cache_dir.glob('*.json'):
                with open(metadata_file, 'r') as f:
                    metadata = json.load(f)
                
                cache_file = metadata_file.with_suffix('.pkl')
                metadata['exists'] = cache_file.exists()
                metadata['size_mb'] = cache_file.stat().st_size / (1024 * 1024) if cache_file.exists() else 0
                
                caches.append(metadata)
            
            cache_info[s] = caches
        
        return cache_info
    
    def _get_cache_dir(self, stage: str) -> Path:
        """Get the cache directory for a stage"""
        if stage == 'features':
            return self.features_cache
        elif stage == 'preprocessing':
            return self.preprocessing_cache
        elif stage == 'training':
            return self.models_cache
        else:
            raise ValueError(f"Unknown stage: {stage}")
    
    def clear_cache(self, stage: Optional[str] = None, older_than_days: Optional[int] = None):
        """
        Clear cached data.
        
        Args:
            stage: If specified, only clear this stage. Otherwise clear all.
            older_than_days: If specified, only clear caches older than this
        """
        stages = [stage] if stage else ['features', 'preprocessing', 'training']
        
        total_cleared = 0
        total_size_mb = 0
        
        for s in stages:
            cache_dir = self._get_cache_dir(s)
            
            for cache_file in cache_dir.glob('*.pkl'):
                metadata_file = cache_file.with_suffix('.json')
                
                should_delete = True
                
                if older_than_days and metadata_file.exists():
                    with open(metadata_file, 'r') as f:
                        metadata = json.load(f)
                    
                    created = datetime.fromisoformat(metadata['created'])
                    age_days = (datetime.now() - created).days
                    
                    should_delete = age_days > older_than_days
                
                if should_delete:
                    size_mb = cache_file.stat().st_size / (1024 * 1024)
                    cache_file.unlink()
                    if metadata_file.exists():
                        metadata_file.unlink()
                    
                    total_cleared += 1
                    total_size_mb += size_mb
        
        print(f"🗑️  Cleared {total_cleared} cache files ({total_size_mb:.2f} MB)")
    
    def get_cache_size(self, stage: Optional[str] = None) -> float:
        """
        Get total size of caches in MB.
        
        Args:
            stage: If specified, only get size for this stage
        
        Returns:
            Total size in MB
        """
        stages = [stage] if stage else ['features', 'preprocessing', 'training']
        
        total_size = 0
        
        for s in stages:
            cache_dir = self._get_cache_dir(s)
            for cache_file in cache_dir.glob('*.pkl'):
                total_size += cache_file.stat().st_size
        
        return total_size / (1024 * 1024)
