"""
Data Utilities - Helper functions for data handling

Copyright (c) 2025 Tom White
Licensed under the MIT License

🚫 STUDENTS: DO NOT EDIT THIS FILE
These utilities are used internally by the pipeline.

Utilities provided:
- Data validation
- File path resolution
- Data summarization
- Train/test split helpers
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional, List, Dict, Any, Tuple
from omegaconf import DictConfig


def validate_csv_file(file_path: Path, required_columns: Optional[List[str]] = None) -> bool:
    """
    Validate that a CSV file exists and has required structure.
    
    Args:
        file_path: Path to CSV file
        required_columns: List of columns that must be present
    
    Returns:
        True if valid
    
    Raises:
        FileNotFoundError: If file doesn't exist
        ValueError: If required columns are missing
    """
    if not file_path.exists():
        raise FileNotFoundError(f"CSV file not found: {file_path}")
    
    try:
        df = pd.read_csv(file_path, nrows=1)  # Just read header
    except Exception as e:
        raise ValueError(f"Failed to read CSV file: {e}")
    
    if required_columns:
        missing = [col for col in required_columns if col not in df.columns]
        if missing:
            raise ValueError(
                f"Required columns missing from CSV: {missing}\n"
                f"Available columns: {list(df.columns)}"
            )
    
    return True


def summarize_dataframe(df: pd.DataFrame) -> Dict[str, Any]:
    """
    Create a summary of a dataframe.
    
    Args:
        df: DataFrame to summarize
    
    Returns:
        Dictionary with summary statistics
    """
    summary = {
        'n_rows': len(df),
        'n_columns': len(df.columns),
        'columns': list(df.columns),
        'dtypes': df.dtypes.value_counts().to_dict(),
        'missing_values': df.isnull().sum().to_dict(),
        'memory_mb': df.memory_usage(deep=True).sum() / (1024 * 1024),
    }
    
    # Numeric column stats
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    if len(numeric_cols) > 0:
        summary['numeric_stats'] = {
            'n_numeric_columns': len(numeric_cols),
            'mean': df[numeric_cols].mean().to_dict(),
            'std': df[numeric_cols].std().to_dict(),
            'min': df[numeric_cols].min().to_dict(),
            'max': df[numeric_cols].max().to_dict(),
        }
    
    return summary


def print_data_summary(df: pd.DataFrame, name: str = "Dataset"):
    """
    Print a formatted summary of a dataframe.
    
    Args:
        df: DataFrame to summarize
        name: Name to display
    """
    print(f"\n{'='*60}")
    print(f"📊 {name} Summary")
    print(f"{'='*60}")
    
    summary = summarize_dataframe(df)
    
    print(f"Rows: {summary['n_rows']:,}")
    print(f"Columns: {summary['n_columns']}")
    print(f"Memory: {summary['memory_mb']:.2f} MB")
    
    # Missing values
    missing = {k: v for k, v in summary['missing_values'].items() if v > 0}
    if missing:
        print(f"\n⚠️  Missing values:")
        for col, count in missing.items():
            pct = (count / summary['n_rows']) * 100
            print(f"  {col}: {count} ({pct:.1f}%)")
    else:
        print(f"\n✅ No missing values")
    
    # Data types
    print(f"\nData types:")
    for dtype, count in summary['dtypes'].items():
        print(f"  {dtype}: {count} columns")
    
    # Numeric stats (sample)
    if 'numeric_stats' in summary:
        print(f"\nNumeric columns: {summary['numeric_stats']['n_numeric_columns']}")
        print(f"Value ranges (min-max):")
        means = summary['numeric_stats']['mean']
        mins = summary['numeric_stats']['min']
        maxs = summary['numeric_stats']['max']
        
        # Show first 5 numeric columns
        for i, col in enumerate(list(means.keys())[:5]):
            print(f"  {col}: [{mins[col]:.3f}, {maxs[col]:.3f}] (mean: {means[col]:.3f})")
        
        if len(means) > 5:
            print(f"  ... and {len(means) - 5} more")
    
    print(f"{'='*60}\n")


def check_data_distribution(df: pd.DataFrame, target_col: str) -> Dict[str, Any]:
    """
    Check the distribution of the target variable.
    
    Args:
        df: DataFrame
        target_col: Name of target column
    
    Returns:
        Dictionary with distribution info
    """
    if target_col not in df.columns:
        raise ValueError(f"Target column '{target_col}' not found in data")
    
    target = df[target_col]
    
    distribution = {
        'mean': float(target.mean()),
        'std': float(target.std()),
        'min': float(target.min()),
        'max': float(target.max()),
        'median': float(target.median()),
        'q25': float(target.quantile(0.25)),
        'q75': float(target.quantile(0.75)),
        'n_unique': int(target.nunique()),
    }
    
    # Check for potential issues
    issues = []
    
    if distribution['std'] < 0.01:
        issues.append("Very low variance in target (std < 0.01)")
    
    if distribution['n_unique'] < 10:
        issues.append(f"Only {distribution['n_unique']} unique target values")
    
    if target.isnull().any():
        issues.append(f"{target.isnull().sum()} missing values in target")
    
    distribution['issues'] = issues
    
    return distribution


def resolve_data_path(config: DictConfig) -> Path:
    """
    Resolve the data file path from config.
    
    Handles relative paths, environment variables, etc.
    
    Args:
        config: Configuration dict
    
    Returns:
        Resolved absolute path
    """
    data_path = Path(config.data.data_path)
    
    # If relative path, make it relative to project root
    if not data_path.is_absolute():
        # Assume we're in src/neuro_smell/utils, so go up 3 levels
        project_root = Path(__file__).parent.parent.parent.parent
        data_path = project_root / data_path
    
    return data_path.resolve()


def split_by_stratification(
    df: pd.DataFrame,
    target_col: str,
    test_size: float = 0.2,
    n_bins: int = 5,
    random_state: int = 42
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Split data with stratification for regression targets.
    
    Bins the target variable and stratifies on bins to ensure
    similar distributions in train and test sets.
    
    Args:
        df: DataFrame to split
        target_col: Name of target column
        test_size: Fraction for test set
        n_bins: Number of bins for stratification
        random_state: Random seed
    
    Returns:
        (train_df, test_df)
    """
    from sklearn.model_selection import train_test_split
    
    # Create bins for stratification
    df['_stratify_bin'] = pd.qcut(df[target_col], q=n_bins, labels=False, duplicates='drop')
    
    # Split with stratification
    train_df, test_df = train_test_split(
        df,
        test_size=test_size,
        stratify=df['_stratify_bin'],
        random_state=random_state
    )
    
    # Remove temporary column
    train_df = train_df.drop('_stratify_bin', axis=1)
    test_df = test_df.drop('_stratify_bin', axis=1)
    
    return train_df, test_df


def save_data_splits(
    train_df: pd.DataFrame,
    val_df: pd.DataFrame,
    test_df: pd.DataFrame,
    output_dir: Path,
    prefix: str = ""
):
    """
    Save train/val/test splits to CSV files.
    
    Args:
        train_df: Training data
        val_df: Validation data
        test_df: Test data
        output_dir: Directory to save files
        prefix: Optional prefix for filenames
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    prefix = f"{prefix}_" if prefix else ""
    
    train_path = output_dir / f"{prefix}train.csv"
    val_path = output_dir / f"{prefix}val.csv"
    test_path = output_dir / f"{prefix}test.csv"
    
    train_df.to_csv(train_path, index=False)
    val_df.to_csv(val_path, index=False)
    test_df.to_csv(test_path, index=False)
    
    print(f"💾 Saved data splits:")
    print(f"  Train: {train_path} ({len(train_df)} samples)")
    print(f"  Val: {val_path} ({len(val_df)} samples)")
    print(f"  Test: {test_path} ({len(test_df)} samples)")
