"""
Custom Metrics for Model Evaluation

Copyright (c) 2025 Tom White
Licensed under the MIT License

🚫 STUDENTS: DO NOT EDIT THIS FILE
These metrics are automatically computed during training.

Metrics implemented:
- Pearson correlation: Primary metric for odor prediction
- R² score: Variance explained
- Mean absolute error: Average prediction error
- Root mean squared error: Penalizes large errors
"""

import torch
import numpy as np
from typing import Union, Tuple


def pearson_correlation(predictions: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """
    Compute Pearson correlation coefficient between predictions and targets.
    
    This is the primary metric for olfactory prediction tasks.
    Range: [-1, 1] where 1 is perfect positive correlation.
    
    Args:
        predictions: Model predictions [batch_size, n_outputs]
        targets: True values [batch_size, n_outputs]
    
    Returns:
        Pearson correlation coefficient
    """
    # Center the data (subtract mean)
    pred_mean = predictions.mean(dim=0, keepdim=True)
    target_mean = targets.mean(dim=0, keepdim=True)
    
    pred_centered = predictions - pred_mean
    target_centered = targets - target_mean
    
    # Compute correlation
    numerator = (pred_centered * target_centered).sum(dim=0)
    
    pred_std = pred_centered.pow(2).sum(dim=0).sqrt()
    target_std = target_centered.pow(2).sum(dim=0).sqrt()
    denominator = pred_std * target_std
    
    # Avoid division by zero
    correlation = numerator / (denominator + 1e-8)
    
    # Average across all outputs
    return correlation.mean()


def r2_score(predictions: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """
    Compute R² (coefficient of determination).
    
    R² = 1 - (SS_res / SS_tot)
    where SS_res is sum of squared residuals and SS_tot is total sum of squares.
    
    Range: (-∞, 1] where 1 is perfect prediction.
    
    Args:
        predictions: Model predictions [batch_size, n_outputs]
        targets: True values [batch_size, n_outputs]
    
    Returns:
        R² score
    """
    target_mean = targets.mean(dim=0, keepdim=True)
    
    ss_tot = ((targets - target_mean) ** 2).sum(dim=0)
    ss_res = ((targets - predictions) ** 2).sum(dim=0)
    
    r2 = 1 - (ss_res / (ss_tot + 1e-8))
    
    return r2.mean()


def mean_absolute_error(predictions: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """
    Compute mean absolute error (MAE).
    
    MAE = mean(|predictions - targets|)
    
    Lower is better (0 is perfect).
    
    Args:
        predictions: Model predictions [batch_size, n_outputs]
        targets: True values [batch_size, n_outputs]
    
    Returns:
        MAE
    """
    return torch.abs(predictions - targets).mean()


def root_mean_squared_error(predictions: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """
    Compute root mean squared error (RMSE).
    
    RMSE = sqrt(mean((predictions - targets)²))
    
    Lower is better (0 is perfect).
    Penalizes large errors more than MAE.
    
    Args:
        predictions: Model predictions [batch_size, n_outputs]
        targets: True values [batch_size, n_outputs]
    
    Returns:
        RMSE
    """
    return torch.sqrt(((predictions - targets) ** 2).mean())


def compute_all_metrics(predictions: torch.Tensor, targets: torch.Tensor) -> dict:
    """
    Compute all metrics at once.
    
    Args:
        predictions: Model predictions [batch_size, n_outputs]
        targets: True values [batch_size, n_outputs]
    
    Returns:
        Dictionary with all metrics
    """
    return {
        'pearson_corr': pearson_correlation(predictions, targets).item(),
        'r2': r2_score(predictions, targets).item(),
        'mae': mean_absolute_error(predictions, targets).item(),
        'rmse': root_mean_squared_error(predictions, targets).item(),
    }


def numpy_pearson_correlation(predictions: np.ndarray, targets: np.ndarray) -> float:
    """
    NumPy version of Pearson correlation (for non-PyTorch contexts).
    
    Args:
        predictions: Model predictions [n_samples, n_outputs]
        targets: True values [n_samples, n_outputs]
    
    Returns:
        Pearson correlation coefficient
    """
    # Flatten if multi-output
    pred_flat = predictions.flatten()
    target_flat = targets.flatten()
    
    # Compute correlation
    pred_mean = pred_flat.mean()
    target_mean = target_flat.mean()
    
    numerator = ((pred_flat - pred_mean) * (target_flat - target_mean)).sum()
    
    pred_std = np.sqrt(((pred_flat - pred_mean) ** 2).sum())
    target_std = np.sqrt(((target_flat - target_mean) ** 2).sum())
    denominator = pred_std * target_std
    
    return numerator / (denominator + 1e-8)
