#!/usr/bin/env python3
"""Quick test of visualization features (minimal epochs)."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

import torch
import numpy as np
from src.olfactory_modeling.data.activity_map_dataset import MoleculeActivityMapDataset
from src.olfactory_modeling.models.baseline_nn import get_model
from src.olfactory_modeling.pipeline.train_nn import train_nn
from src.olfactory_modeling.visualization import (
    plot_training_curves,
    plot_prediction_scatter,
    plot_activity_map_comparison,
    create_training_report,
)

print("="*70)
print("QUICK VISUALIZATION TEST")
print("="*70)

# Load dataset
print("\n1. Loading dataset...")
dataset = MoleculeActivityMapDataset(
    processed_dir="data/02_processed",
    split=None,
    random_seed=42,
)
print(f"   ✓ Loaded {len(dataset)} molecules")

# Create data loaders
from torch.utils.data import DataLoader, Subset
train_subset = Subset(dataset, list(range(200)))
val_subset = Subset(dataset, list(range(200, 243)))
test_subset = Subset(dataset, list(range(243, 287)))

train_loader = DataLoader(train_subset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_subset, batch_size=32, shuffle=False)
test_loader = DataLoader(test_subset, batch_size=32, shuffle=False)

# Train with just 5 epochs to test visualization
print("\n2. Quick training (5 epochs)...")
model = get_model('mlp', input_dim=268, output_shape=(79, 43), dropout=0.35)

metrics = train_nn(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    output_dir="viz/quick_test",
    num_epochs=5,
    learning_rate=0.005,
    device=torch.device('cpu'),  # Use CPU for speed
    verbose=False,
)

print(f"   ✓ Training complete! Best epoch: {metrics['best_epoch']}")
print(f"   ✓ Auto-generated: viz/quick_test/training_curves.png")

# Get test predictions
print("\n3. Generating predictions...")
model.eval()
all_preds = []
all_targets = []

with torch.no_grad():
    for features, targets, _ in test_loader:
        predictions = model(features).cpu().numpy()
        all_preds.append(predictions)
        all_targets.append(targets.numpy())

all_preds = np.concatenate(all_preds, axis=0)
all_targets = np.concatenate(all_targets, axis=0)

#4. Test standalone visualizations
print("\n4. Testing standalone visualization functions...")

# Prediction scatter
fig = plot_prediction_scatter(
    all_preds,
    all_targets,
    output_path='viz/quick_test/prediction_scatter.png',
    title='Test Set Predictions'
)
print("   ✓ Prediction scatter saved")

# Activity map comparison
fig = plot_activity_map_comparison(
    all_preds,
    all_targets,
    n_samples=3,
    output_path='viz/quick_test/activity_maps.png'
)
print("   ✓ Activity map comparison saved")

# Comprehensive report
fig = create_training_report(
    metrics,
    predictions=all_preds,
    targets=all_targets,
    output_path='viz/quick_test/full_report.png'
)
print("   ✓ Full training report saved")

print("\n" + "="*70)
print("VISUALIZATION TEST COMPLETE ✅")
print("="*70)
print("\nGenerated files in viz/quick_test/:")
print("  - training_curves.png (auto-generated by train_nn)")
print("  - prediction_scatter.png")
print("  - activity_maps.png")
print("  - full_report.png")
print("\nAll visualization functions working!")
print("="*70)
