"""
Feature Extraction Stage - Extract molecular descriptors from SMILES

Copyright (c) 2025 Tom White
Licensed under the MIT License

🚫 STUDENTS: DO NOT EDIT THIS FILE
Feature extraction is configured in configs/data/your_dataset.yaml

This stage:
- Loads SMILES strings from CSV
- Computes RDKit molecular descriptors
- Saves features for preprocessing stage
- Caches results (5-10 min savings!)

Based on: legacy/build.py
Improvements: Caching, better error handling, progress tracking
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional, Dict, Any
from tqdm import tqdm
from omegaconf import DictConfig

# Molecular descriptor libraries
try:
    from rdkit import Chem
    from rdkit.Chem import Descriptors, Lipinski
    from rdkit.ML.Descriptors import MoleculeDescriptors
except ImportError:
    raise ImportError(
        "RDKit is required for feature extraction.\n"
        "Install with: conda install -c conda-forge rdkit"
    )

try:
    import pyrfume
except ImportError:
    print("⚠️  Warning: PyRfume not installed. Some features may not be available.")
    pyrfume = None


class FeatureExtractor:
    """
    Extract molecular descriptors from SMILES strings.
    
    Uses RDKit to compute physicochemical properties and structural features.
    """
    
    def __init__(self, config: DictConfig):
        """
        Args:
            config: Configuration dict with data settings
        """
        self.config = config
        
        # Get list of descriptors to compute
        self.descriptor_names = self._get_descriptor_names()
        self.calculator = MoleculeDescriptors.MolecularDescriptorCalculator(
            self.descriptor_names
        )
        
        print(f"📊 Feature extractor initialized with {len(self.descriptor_names)} descriptors")
    
    def _get_descriptor_names(self):
        """Get list of RDKit descriptor names to compute"""
        # Use all available 2D descriptors
        # (Excludes 3D descriptors which require conformer generation)
        available_descriptors = [desc[0] for desc in Descriptors._descList]
        
        # Filter out 3D descriptors (they're slower and require 3D structure)
        descriptors_2d = [
            d for d in available_descriptors
            if not any(x in d for x in ['3D', 'PMI', 'Inertia', 'Eccentricity', 'Asphericity', 'SpherocityIndex'])
        ]
        
        return descriptors_2d
    
    def smiles_to_features(self, smiles: str) -> Optional[np.ndarray]:
        """
        Convert a SMILES string to molecular descriptors.
        
        Args:
            smiles: SMILES string
        
        Returns:
            Array of descriptors, or None if conversion failed
        """
        try:
            # Parse SMILES
            mol = Chem.MolFromSmiles(smiles)
            
            if mol is None:
                return None
            
            # Compute descriptors
            descriptors = self.calculator.CalcDescriptors(mol)
            
            # Convert to numpy array
            features = np.array(descriptors, dtype=np.float32)
            
            # Check for invalid values
            if np.any(np.isnan(features)) or np.any(np.isinf(features)):
                return None
            
            return features
        
        except Exception as e:
            # Silently handle errors (will be reported in summary)
            return None
    
    def extract_from_dataframe(
        self,
        df: pd.DataFrame,
        smiles_column: str = 'SMILES',
        show_progress: bool = True
    ) -> pd.DataFrame:
        """
        Extract features for all molecules in a dataframe.
        
        Args:
            df: DataFrame with SMILES column
            smiles_column: Name of column containing SMILES
            show_progress: Whether to show progress bar
        
        Returns:
            DataFrame with original data + molecular descriptors
        """
        if smiles_column not in df.columns:
            raise ValueError(
                f"SMILES column '{smiles_column}' not found in data.\n"
                f"Available columns: {list(df.columns)}"
            )
        
        print(f"\n🧪 Extracting features from {len(df)} molecules...")
        print(f"   SMILES column: {smiles_column}")
        print(f"   Descriptors: {len(self.descriptor_names)}")
        
        # Extract features for each molecule
        features_list = []
        failed_indices = []
        
        iterator = tqdm(df[smiles_column], desc="Extracting") if show_progress else df[smiles_column]
        
        for idx, smiles in enumerate(iterator):
            features = self.smiles_to_features(smiles)
            
            if features is None:
                failed_indices.append(idx)
                # Use NaN for failed conversions (will be dropped later)
                features = np.full(len(self.descriptor_names), np.nan, dtype=np.float32)
            
            features_list.append(features)
        
        # Create features dataframe
        features_array = np.vstack(features_list)
        features_df = pd.DataFrame(
            features_array,
            columns=self.descriptor_names,
            index=df.index
        )
        
        # Combine with original data
        result_df = pd.concat([df, features_df], axis=1)
        
        # Report results
        n_failed = len(failed_indices)
        success_rate = (len(df) - n_failed) / len(df) * 100
        
        print(f"\n✅ Feature extraction complete!")
        print(f"   Success: {len(df) - n_failed}/{len(df)} ({success_rate:.1f}%)")
        
        if n_failed > 0:
            print(f"   ⚠️  Failed: {n_failed} molecules")
            print(f"   Failed indices: {failed_indices[:10]}{'...' if n_failed > 10 else ''}")
            
            # Drop failed molecules
            result_df = result_df.dropna(subset=self.descriptor_names)
            print(f"   Dropped failed molecules. Remaining: {len(result_df)}")
        
        return result_df
    
    def get_feature_info(self) -> Dict[str, Any]:
        """Get information about the features"""
        return {
            'n_features': len(self.descriptor_names),
            'feature_names': self.descriptor_names,
            'feature_types': 'RDKit 2D molecular descriptors',
        }


def extract_features(
    config: DictConfig,
    cache_manager: Optional[Any] = None,
    force_recompute: bool = False
) -> pd.DataFrame:
    """
    Main function to extract features with optional caching.
    
    Args:
        config: Configuration dict
        cache_manager: Optional CacheManager instance
        force_recompute: Force recomputation even if cache exists
    
    Returns:
        DataFrame with features extracted
    """
    # Check cache first
    if cache_manager and not force_recompute:
        cached_data = cache_manager.load_cache('features')
        if cached_data is not None:
            print("✅ Using cached features")
            return cached_data
    
    # Load raw data
    data_path = Path(config.data.data_path)
    
    if not data_path.exists():
        raise FileNotFoundError(f"Data file not found: {data_path}")
    
    print(f"\n📂 Loading raw data from: {data_path}")
    df = pd.read_csv(data_path)
    print(f"✅ Loaded {len(df)} samples")
    
    # Check if features already exist in the data
    smiles_column = config.data.get('smiles_column', None)
    
    if smiles_column and smiles_column in df.columns:
        # Need to extract features from SMILES
        print(f"\n🧪 SMILES column found: '{smiles_column}'")
        print("   Extracting molecular descriptors...")
        
        extractor = FeatureExtractor(config)
        df_with_features = extractor.extract_from_dataframe(df, smiles_column)
    
    else:
        # Features already in the data
        print("\n✅ Data already contains features (no SMILES column)")
        df_with_features = df
    
    # Cache the results
    if cache_manager:
        cache_manager.save_cache('features', df_with_features)
    
    return df_with_features


def get_feature_summary(df: pd.DataFrame, smiles_column: Optional[str] = None) -> Dict[str, Any]:
    """
    Get summary statistics for extracted features.
    
    Args:
        df: DataFrame with features
        smiles_column: SMILES column to exclude from feature count
    
    Returns:
        Dictionary with summary info
    """
    # Identify feature columns (numeric, not SMILES or target)
    exclude_cols = []
    if smiles_column:
        exclude_cols.append(smiles_column)
    
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    feature_cols = [col for col in numeric_cols if col not in exclude_cols]
    
    features = df[feature_cols]
    
    summary = {
        'n_samples': len(df),
        'n_features': len(feature_cols),
        'feature_names': feature_cols.tolist(),
        'missing_values': features.isnull().sum().sum(),
        'infinite_values': np.isinf(features).sum().sum(),
        'feature_ranges': {
            'min': features.min().min(),
            'max': features.max().max(),
            'mean': features.mean().mean(),
            'std': features.std().mean(),
        }
    }
    
    return summary
