"""
Preprocessing Stage - Optional PCA, scaling, and feature selection

Copyright (c) 2025 Tom White
Licensed under the MIT License

🚫 STUDENTS: DO NOT EDIT THIS FILE
Preprocessing is configured in configs/preprocessing/*.yaml

This stage:
- Scales features (StandardScaler, MinMaxScaler, or RobustScaler)
- Removes low-variance features (optional)
- Applies PCA dimensionality reduction (optional)
- Caches preprocessed data

Based on: legacy/pca.py
Improvements: Optional PCA, multiple scalers, caching, better reporting
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional, Dict, Any, Tuple
from omegaconf import DictConfig

from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.decomposition import PCA
from sklearn.feature_selection import VarianceThreshold


class Preprocessor:
    """
    Flexible preprocessor with optional PCA and feature selection.
    
    Can be configured to:
    - Use or skip PCA
    - Use different scalers
    - Remove low-variance features
    - Save transformation for test data
    """
    
    def __init__(self, config: DictConfig):
        """
        Args:
            config: Configuration dict with preprocessing settings
        """
        self.config = config
        
        # Initialize components (will be fitted during transform)
        self.scaler = None
        self.variance_selector = None
        self.pca = None
        
        # Flags
        self.is_fitted = False
        
        # Store feature names for interpretability
        self.input_features = None
        self.output_features = None
    
    def _init_scaler(self):
        """Initialize the appropriate scaler"""
        scaler_type = self.config.preprocessing.scaling.get('method', 'standard')
        
        if scaler_type == 'standard':
            self.scaler = StandardScaler()
        elif scaler_type == 'minmax':
            self.scaler = MinMaxScaler()
        elif scaler_type == 'robust':
            self.scaler = RobustScaler()
        elif scaler_type == 'none':
            self.scaler = None
        else:
            raise ValueError(f"Unknown scaler type: {scaler_type}")
    
    def _init_variance_selector(self):
        """Initialize variance threshold selector"""
        if self.config.preprocessing.variance_threshold.enabled:
            threshold = self.config.preprocessing.variance_threshold.threshold
            self.variance_selector = VarianceThreshold(threshold=threshold)
        else:
            self.variance_selector = None
    
    def _init_pca(self):
        """Initialize PCA if enabled"""
        if self.config.preprocessing.pca.enabled:
            n_components = self.config.preprocessing.pca.n_components
            
            # Handle 'auto' option (keep components for 95% variance)
            if n_components == 'auto':
                n_components = 0.95
            
            self.pca = PCA(
                n_components=n_components,
                random_state=self.config.preprocessing.pca.get('random_state', 42)
            )
        else:
            self.pca = None
    
    def fit_transform(self, X: np.ndarray, feature_names: Optional[list] = None) -> np.ndarray:
        """
        Fit preprocessor and transform features.
        
        Args:
            X: Feature array [n_samples, n_features]
            feature_names: Optional list of feature names
        
        Returns:
            Transformed features [n_samples, n_output_features]
        """
        print(f"\n🔧 Preprocessing features...")
        print(f"   Input shape: {X.shape}")
        
        self.input_features = feature_names
        
        # Initialize components
        self._init_scaler()
        self._init_variance_selector()
        self._init_pca()
        
        # Step 1: Scaling
        if self.scaler is not None:
            print(f"   Scaling: {self.config.preprocessing.scaling.method}")
            X = self.scaler.fit_transform(X)
        else:
            print("   Scaling: None")
        
        # Step 2: Variance threshold
        if self.variance_selector is not None:
            threshold = self.config.preprocessing.variance_threshold.threshold
            print(f"   Variance threshold: {threshold}")
            
            n_before = X.shape[1]
            X = self.variance_selector.fit_transform(X)
            n_after = X.shape[1]
            n_removed = n_before - n_after
            
            print(f"   Removed {n_removed} low-variance features ({n_removed/n_before*100:.1f}%)")
        
        # Step 3: PCA
        if self.pca is not None:
            print(f"   PCA: {self.config.preprocessing.pca.n_components} components")
            
            n_before = X.shape[1]
            X = self.pca.fit_transform(X)
            n_after = X.shape[1]
            
            # Report variance explained
            variance_explained = self.pca.explained_variance_ratio_.sum()
            print(f"   Reduced from {n_before} to {n_after} features")
            print(f"   Variance explained: {variance_explained*100:.2f}%")
            
            # Store component names
            self.output_features = [f"PC{i+1}" for i in range(n_after)]
        else:
            print("   PCA: Disabled")
            
            if feature_names and self.variance_selector:
                # Track which features survived variance threshold
                selected_mask = self.variance_selector.get_support()
                self.output_features = [f for i, f in enumerate(feature_names) if selected_mask[i]]
            else:
                self.output_features = feature_names
        
        self.is_fitted = True
        
        print(f"   Output shape: {X.shape}")
        print("✅ Preprocessing complete!")
        
        return X
    
    def transform(self, X: np.ndarray) -> np.ndarray:
        """
        Transform new data using fitted preprocessor.
        
        Args:
            X: Feature array [n_samples, n_features]
        
        Returns:
            Transformed features [n_samples, n_output_features]
        """
        if not self.is_fitted:
            raise RuntimeError("Preprocessor must be fitted before transform()")
        
        # Apply transformations in same order
        if self.scaler is not None:
            X = self.scaler.transform(X)
        
        if self.variance_selector is not None:
            X = self.variance_selector.transform(X)
        
        if self.pca is not None:
            X = self.pca.transform(X)
        
        return X
    
    def get_feature_importance(self, n_top: int = 20) -> Optional[pd.DataFrame]:
        """
        Get feature importance from PCA loadings.
        
        Args:
            n_top: Number of top features to return per component
        
        Returns:
            DataFrame with feature importance, or None if no PCA
        """
        if self.pca is None or self.input_features is None:
            return None
        
        # Get PCA loadings (components)
        loadings = self.pca.components_
        
        # Create DataFrame
        importance_df = pd.DataFrame(
            loadings.T,
            columns=[f"PC{i+1}" for i in range(loadings.shape[0])],
            index=self.input_features
        )
        
        return importance_df
    
    def get_preprocessing_info(self) -> Dict[str, Any]:
        """Get information about the preprocessing"""
        info = {
            'is_fitted': self.is_fitted,
            'scaling': self.config.preprocessing.scaling.method if self.scaler else 'none',
            'variance_threshold': self.config.preprocessing.variance_threshold.enabled,
            'pca_enabled': self.config.preprocessing.pca.enabled,
        }
        
        if self.is_fitted:
            info['input_dim'] = len(self.input_features) if self.input_features else None
            info['output_dim'] = len(self.output_features) if self.output_features else None
            
            if self.pca:
                info['pca_components'] = self.pca.n_components_
                info['variance_explained'] = self.pca.explained_variance_ratio_.sum()
        
        return info


def preprocess_data(
    df: pd.DataFrame,
    config: DictConfig,
    target_column: str,
    cache_manager: Optional[Any] = None,
    force_recompute: bool = False
) -> Tuple[pd.DataFrame, Preprocessor]:
    """
    Main function to preprocess features with optional caching.
    
    Args:
        df: DataFrame with extracted features
        config: Configuration dict
        target_column: Name of target column (to exclude from preprocessing)
        cache_manager: Optional CacheManager instance
        force_recompute: Force recomputation even if cache exists
    
    Returns:
        (preprocessed_df, fitted_preprocessor)
    """
    # Check cache first
    if cache_manager and not force_recompute:
        cached_data = cache_manager.load_cache('preprocessing')
        if cached_data is not None:
            print("✅ Using cached preprocessed data")
            return cached_data['df'], cached_data['preprocessor']
    
    # Separate features and target
    exclude_cols = [target_column]
    if config.data.get('smiles_column'):
        exclude_cols.append(config.data.smiles_column)
    
    feature_cols = [col for col in df.columns if col not in exclude_cols]
    
    X = df[feature_cols].values
    feature_names = feature_cols
    
    print(f"\n🔧 Preprocessing {len(feature_names)} features...")
    
    # Create and fit preprocessor
    preprocessor = Preprocessor(config)
    X_preprocessed = preprocessor.fit_transform(X, feature_names)
    
    # Create new dataframe with preprocessed features
    preprocessed_df = pd.DataFrame(
        X_preprocessed,
        columns=preprocessor.output_features,
        index=df.index
    )
    
    # Add back the target column
    preprocessed_df[target_column] = df[target_column]
    
    # Cache the results
    if cache_manager:
        cache_data = {
            'df': preprocessed_df,
            'preprocessor': preprocessor
        }
        cache_manager.save_cache('preprocessing', cache_data)
    
    return preprocessed_df, preprocessor
