"""
Preprocessing Stage - Optional PCA, scaling, and feature selection

Copyright (c) 2025 Tom White
Licensed under the MIT License

🚫 STUDENTS: DO NOT EDIT THIS FILE
Preprocessing is configured in configs/preprocessing/*.yaml

This stage:
- Scales features (StandardScaler, MinMaxScaler, or RobustScaler)
- Removes low-variance features (optional)
- Applies PCA dimensionality reduction (optional)
- Caches preprocessed data

Based on: legacy/pca.py
Improvements: Optional PCA, multiple scalers, caching, better reporting
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional, Dict, Any, Tuple
from omegaconf import DictConfig

from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.decomposition import PCA
from sklearn.feature_selection import VarianceThreshold

# Import PCA masking for legacy replication
from neuro_smell.stages.pca_masking import PCAMasking


class Preprocessor:
    """
    Flexible preprocessor with optional PCA and feature selection.
    
    Can be configured to:
    - Use or skip PCA
    - Use different scalers
    - Remove low-variance features
    - Save transformation for test data
    """
    
    def __init__(self, config: DictConfig):
        """
        Args:
            config: Configuration dict with preprocessing settings
        """
        self.config = config
        
        # Initialize components (will be fitted during transform)
        self.scaler = None
        self.variance_selector = None
        self.pca = None
        self.pca_masker = None  # For PCA masking approach (legacy/pca_copy.py)
        self.pca_mask = None  # Boolean mask from PCA masking
        
        # Flags
        self.is_fitted = False
        self.use_pca_masking = False  # Track which PCA approach is used
        
        # Store feature names for interpretability
        self.input_features = None
        self.output_features = None
    
    def _init_scaler(self):
        """Initialize the appropriate scaler"""
        scaler_type = self.config.preprocessing.scaling.get('method', 'standard')
        
        if scaler_type == 'standard':
            self.scaler = StandardScaler()
        elif scaler_type == 'minmax':
            self.scaler = MinMaxScaler()
        elif scaler_type == 'robust':
            self.scaler = RobustScaler()
        elif scaler_type == 'none':
            self.scaler = None
        else:
            raise ValueError(f"Unknown scaler type: {scaler_type}")
    
    def _init_variance_selector(self):
        """Initialize variance threshold selector"""
        if self.config.preprocessing.variance_threshold.enabled:
            threshold = self.config.preprocessing.variance_threshold.threshold
            self.variance_selector = VarianceThreshold(threshold=threshold)
        else:
            self.variance_selector = None
    
    def _init_pca(self):
        """Initialize PCA or PCA masking if enabled"""
        if not self.config.preprocessing.pca.enabled:
            self.pca = None
            self.pca_masker = None
            self.use_pca_masking = False
            return
        
        n_components = self.config.preprocessing.pca.n_components
        
        # Handle 'auto' option (keep components for 95% variance)
        if n_components == 'auto':
            n_components = 0.95
        
        # Check if using PCA masking approach (from legacy/pca_copy.py)
        self.use_pca_masking = self.config.preprocessing.pca.get('use_masking', False)
        
        if self.use_pca_masking:
            # Use PCA masking: PCA for feature importance, mask applied to original features
            masking_threshold = self.config.preprocessing.pca.get('masking_threshold', 0.1)
            random_state = self.config.preprocessing.pca.get('random_state', 42)
            
            self.pca_masker = PCAMasking(
                n_components=n_components,
                threshold=masking_threshold,
                random_state=random_state
            )
            self.pca = None  # Not using standard PCA transformation
        else:
            # Standard PCA transformation
            self.pca = PCA(
                n_components=n_components,
                random_state=self.config.preprocessing.pca.get('random_state', 42)
            )
            self.pca_masker = None
    
    def fit_transform(self, X: np.ndarray, feature_names: Optional[list] = None) -> np.ndarray:
        """
        Fit preprocessor and transform features.
        
        Args:
            X: Feature array [n_samples, n_features]
            feature_names: Optional list of feature names
        
        Returns:
            Transformed features [n_samples, n_output_features]
        """
        print(f"\n🔧 Preprocessing features...")
        print(f"   Input shape: {X.shape}")
        
        self.input_features = feature_names
        
        # Initialize components
        self._init_scaler()
        self._init_variance_selector()
        self._init_pca()
        
        # Step 1: Scaling
        if self.scaler is not None:
            print(f"   Scaling: {self.config.preprocessing.scaling.method}")
            X = self.scaler.fit_transform(X)
        else:
            print("   Scaling: None")
        
        # Step 2: Variance threshold
        if self.variance_selector is not None:
            threshold = self.config.preprocessing.variance_threshold.threshold
            print(f"   Variance threshold: {threshold}")
            
            n_before = X.shape[1]
            X = self.variance_selector.fit_transform(X)
            n_after = X.shape[1]
            n_removed = n_before - n_after
            
            print(f"   Removed {n_removed} low-variance features ({n_removed/n_before*100:.1f}%)")
        
        # Step 3: PCA or PCA Masking
        if self.use_pca_masking and self.pca_masker is not None:
            # PCA Masking approach (legacy/pca_copy.py)
            print(f"   PCA Masking: {self.config.preprocessing.pca.n_components} components, "
                  f"threshold={self.config.preprocessing.pca.get('masking_threshold', 0.1)}")
            
            # Store pre-masking features for transform
            X_scaled = X.copy()
            
            n_before = X.shape[1]
            X, self.pca_mask = self.pca_masker.fit_transform(X)
            n_after = X.shape[1]
            
            # Report results (printed by pca_masker.fit_transform)
            
            # Generate visualizations if enabled
            if self.config.preprocessing.pca.get('visualize', False):
                from pathlib import Path
                exp_dir = Path(self.config.paths.experiments) / self.config.experiment_name
                viz_dir = exp_dir / self.config.preprocessing.pca.get('visualization_dir', 'pca_analysis')
                
                self.pca_masker.visualize(str(viz_dir))
                
                # Save mask if requested
                if self.config.preprocessing.pca.get('save_mask', False):
                    mask_path = viz_dir / 'feature_mask.csv'
                    self.pca_masker.save_mask(str(mask_path))
            
            # Store masked feature names
            if feature_names and self.variance_selector:
                selected_mask = self.variance_selector.get_support()
                selected_features = [f for i, f in enumerate(feature_names) if selected_mask[i]]
                # Apply PCA mask to selected features
                self.output_features = [f for i, f in enumerate(selected_features) if self.pca_mask[i]]
            else:
                self.output_features = [f"masked_feature_{i}" for i in range(n_after)]
                
        elif self.pca is not None:
            # Standard PCA transformation
            print(f"   PCA: {self.config.preprocessing.pca.n_components} components")
            
            n_before = X.shape[1]
            X = self.pca.fit_transform(X)
            n_after = X.shape[1]
            
            # Report variance explained
            variance_explained = self.pca.explained_variance_ratio_.sum()
            print(f"   Reduced from {n_before} to {n_after} features")
            print(f"   Variance explained: {variance_explained*100:.2f}%")
            
            # Store component names
            self.output_features = [f"PC{i+1}" for i in range(n_after)]
        else:
            print("   PCA: Disabled")
            
            if feature_names and self.variance_selector:
                # Track which features survived variance threshold
                selected_mask = self.variance_selector.get_support()
                self.output_features = [f for i, f in enumerate(feature_names) if selected_mask[i]]
            else:
                self.output_features = feature_names
        
        self.is_fitted = True
        
        print(f"   Output shape: {X.shape}")
        print("✅ Preprocessing complete!")
        
        return X
    
    def transform(self, X: np.ndarray) -> np.ndarray:
        """
        Transform new data using fitted preprocessor.
        
        Args:
            X: Feature array [n_samples, n_features]
        
        Returns:
            Transformed features [n_samples, n_output_features]
        """
        if not self.is_fitted:
            raise RuntimeError("Preprocessor must be fitted before transform()")
        
        # Apply transformations in same order
        if self.scaler is not None:
            X = self.scaler.transform(X)
        
        if self.variance_selector is not None:
            X = self.variance_selector.transform(X)
        
        # Apply PCA or PCA masking
        if self.use_pca_masking and self.pca_masker is not None:
            # Apply mask to original scaled features
            X = self.pca_masker.transform(X)
        elif self.pca is not None:
            # Apply standard PCA transformation
            X = self.pca.transform(X)
        
        return X
    
    def get_feature_importance(self, n_top: int = 20) -> Optional[pd.DataFrame]:
        """
        Get feature importance from PCA loadings.
        
        Args:
            n_top: Number of top features to return per component
        
        Returns:
            DataFrame with feature importance, or None if no PCA
        """
        if self.pca is None or self.input_features is None:
            return None
        
        # Get PCA loadings (components)
        loadings = self.pca.components_
        
        # Create DataFrame
        importance_df = pd.DataFrame(
            loadings.T,
            columns=[f"PC{i+1}" for i in range(loadings.shape[0])],
            index=self.input_features
        )
        
        return importance_df
    
    def get_preprocessing_info(self) -> Dict[str, Any]:
        """Get information about the preprocessing"""
        info = {
            'is_fitted': self.is_fitted,
            'scaling': self.config.preprocessing.scaling.method if self.scaler else 'none',
            'variance_threshold': self.config.preprocessing.variance_threshold.enabled,
            'pca_enabled': self.config.preprocessing.pca.enabled,
            'pca_masking_enabled': self.use_pca_masking,
        }
        
        if self.is_fitted:
            info['input_dim'] = len(self.input_features) if self.input_features else None
            info['output_dim'] = len(self.output_features) if self.output_features else None
            
            if self.pca:
                # Standard PCA
                info['pca_components'] = self.pca.n_components_
                info['variance_explained'] = self.pca.explained_variance_ratio_.sum()
            elif self.pca_masker:
                # PCA Masking
                masker_info = self.pca_masker.get_info()
                info['pca_components'] = masker_info.get('n_components')
                info['variance_explained'] = masker_info.get('variance_explained')
                info['masking_threshold'] = masker_info.get('threshold')
                info['features_selected'] = masker_info.get('features_selected')
                info['reduction_percent'] = masker_info.get('reduction_percent')
        
        return info


def preprocess_data(
    df: pd.DataFrame,
    config: DictConfig,
    target_column: str,
    cache_manager: Optional[Any] = None,
    force_recompute: bool = False
) -> Tuple[pd.DataFrame, Preprocessor]:
    """
    Main function to preprocess features with optional caching.
    
    Args:
        df: DataFrame with extracted features
        config: Configuration dict
        target_column: Name of target column (to exclude from preprocessing)
        cache_manager: Optional CacheManager instance
        force_recompute: Force recomputation even if cache exists
    
    Returns:
        (preprocessed_df, fitted_preprocessor)
    """
    # Check cache first
    if cache_manager and not force_recompute:
        cached_data = cache_manager.load_cache('preprocessing')
        if cached_data is not None:
            print("✅ Using cached preprocessed data")
            return cached_data['df'], cached_data['preprocessor']
    
    # Separate features and target
    exclude_cols = [target_column]
    if config.data.get('smiles_column'):
        exclude_cols.append(config.data.smiles_column)
    
    feature_cols = [col for col in df.columns if col not in exclude_cols]
    
    X = df[feature_cols].values
    feature_names = feature_cols
    
    print(f"\n🔧 Preprocessing {len(feature_names)} features...")
    
    # Create and fit preprocessor
    preprocessor = Preprocessor(config)
    X_preprocessed = preprocessor.fit_transform(X, feature_names)
    
    # Create new dataframe with preprocessed features
    preprocessed_df = pd.DataFrame(
        X_preprocessed,
        columns=preprocessor.output_features,
        index=df.index
    )
    
    # Add back the target column
    preprocessed_df[target_column] = df[target_column]
    
    # Cache the results
    if cache_manager:
        cache_data = {
            'df': preprocessed_df,
            'preprocessor': preprocessor
        }
        cache_manager.save_cache('preprocessing', cache_data)
    
    return preprocessed_df, preprocessor


def prepare_training_data(
    molecular_features_df: pd.DataFrame,
    brain_pca_scores_path: str,
    cid_column: str = 'CID'
) -> Tuple[np.ndarray, np.ndarray, pd.Index, Dict[str, Any]]:
    """
    Align molecular features (X) with brain PCA scores (y) for training.
    
    This is the CRITICAL alignment step that ensures:
    1. Molecular features and brain targets correspond to the same molecules
    2. Both X and y have matching indices (CIDs)
    3. Data is ready for model training: X → y
    
    Args:
        molecular_features_df: DataFrame with molecular features (544 cols after preprocessing)
                               Must have CID as index or column
        brain_pca_scores_path: Path to brain_pca_scores.csv (287 × 5 PCA scores)
        cid_column: Name of CID column/index
    
    Returns:
        X: Molecular features array (n_samples × 544)
        y: Brain PCA scores array (n_samples × 5)
        common_cids: CIDs present in both datasets
        metadata: Dict with alignment statistics
    
    Raises:
        ValueError: If no common CIDs found or data shapes don't match
    
    Example:
        >>> # After feature extraction and preprocessing
        >>> molecular_features = pd.read_csv('data/02_processed/selected_features.csv')
        >>> X, y, cids, meta = prepare_training_data(
        ...     molecular_features,
        ...     'data/02_processed/brain_pca_scores.csv'
        ... )
        >>> # Now ready for training: model.fit(X, y)
    """
    print("\n" + "="*80)
    print("ALIGNING MOLECULAR FEATURES WITH BRAIN PCA TARGETS")
    print("="*80)
    
    # Load brain PCA scores
    print(f"\n1. Loading brain PCA scores from {brain_pca_scores_path}...")
    brain_pca_df = pd.read_csv(brain_pca_scores_path)
    
    if 'CID' not in brain_pca_df.columns:
        raise ValueError(
            f"brain_pca_scores.csv must have 'CID' column. "
            f"Found columns: {brain_pca_df.columns.tolist()}"
        )
    
    # Set CID as index for brain targets
    brain_pca_df = brain_pca_df.set_index('CID')
    print(f"   Loaded {len(brain_pca_df)} brain PCA targets")
    print(f"   Target shape: {brain_pca_df.shape}")
    print(f"   Target columns: {brain_pca_df.columns.tolist()}")
    
    # Prepare molecular features
    print(f"\n2. Preparing molecular features...")
    
    # Check if CID is index or column
    if cid_column in molecular_features_df.columns:
        print(f"   Using '{cid_column}' column as index")
        molecular_features_df = molecular_features_df.set_index(cid_column)
    elif molecular_features_df.index.name == cid_column:
        print(f"   CID already set as index")
    else:
        # Try to use existing index
        print(f"   Using existing index as CID")
        molecular_features_df.index.name = cid_column
    
    print(f"   Molecular features shape: {molecular_features_df.shape}")
    
    # Find common CIDs (intersection)
    print(f"\n3. Finding common molecules...")
    
    # Use indices directly (keep native dtype - usually int64)
    molecular_cids = molecular_features_df.index
    brain_cids = brain_pca_df.index
    
    common_cids = molecular_cids.intersection(brain_cids)
    
    if len(common_cids) == 0:
        raise ValueError(
            "No common CIDs found between molecular features and brain PCA scores!\n"
            f"Molecular CIDs sample: {molecular_cids[:10].tolist()}\n"
            f"Brain CIDs sample: {brain_cids[:10].tolist()}"
        )
    
    print(f"   Molecular features: {len(molecular_cids)} unique CIDs")
    print(f"   Brain PCA targets: {len(brain_cids)} unique CIDs")
    print(f"   Common CIDs: {len(common_cids)} ✅")
    
    # Show CIDs that are missing
    missing_in_brain = set(molecular_cids) - set(brain_cids)
    missing_in_molecular = set(brain_cids) - set(molecular_cids)
    
    if missing_in_brain:
        print(f"   ⚠️ {len(missing_in_brain)} CIDs in molecular but not brain data")
        if len(missing_in_brain) <= 5:
            print(f"      Missing CIDs: {sorted(missing_in_brain)}")
    
    if missing_in_molecular:
        print(f"   ⚠️ {len(missing_in_molecular)} CIDs in brain but not molecular data")
        if len(missing_in_molecular) <= 5:
            print(f"      Missing CIDs: {sorted(missing_in_molecular)}")
    
    # Align data by common CIDs
    print(f"\n4. Aligning datasets...")
    X_df = molecular_features_df.loc[common_cids]
    y_df = brain_pca_df.loc[common_cids]
    
    # Convert to numpy arrays
    X = X_df.values
    y = y_df.values
    
    print(f"   ✅ Aligned X shape: {X.shape}")
    print(f"   ✅ Aligned y shape: {y.shape}")
    
    # Data quality checks
    print(f"\n5. Data quality checks...")
    
    # Check for NaN values
    x_nans = np.isnan(X).sum()
    y_nans = np.isnan(y).sum()
    
    if x_nans > 0:
        print(f"   ⚠️ X contains {x_nans} NaN values ({x_nans/X.size*100:.2f}%)")
    else:
        print(f"   ✅ X has no NaN values")
    
    if y_nans > 0:
        print(f"   ⚠️ y contains {y_nans} NaN values ({y_nans/y.size*100:.2f}%)")
    else:
        print(f"   ✅ y has no NaN values")
    
    # Check for infinite values
    x_infs = np.isinf(X).sum()
    y_infs = np.isinf(y).sum()
    
    if x_infs > 0:
        print(f"   ⚠️ X contains {x_infs} infinite values")
    else:
        print(f"   ✅ X has no infinite values")
    
    if y_infs > 0:
        print(f"   ⚠️ y contains {y_infs} infinite values")
    else:
        print(f"   ✅ y has no infinite values")
    
    # Statistics
    print(f"\n6. Summary statistics...")
    print(f"   X statistics:")
    print(f"      Mean: {X.mean():.4f}")
    print(f"      Std:  {X.std():.4f}")
    print(f"      Min:  {X.min():.4f}")
    print(f"      Max:  {X.max():.4f}")
    
    print(f"   y statistics:")
    print(f"      Mean: {y.mean(axis=0)}")
    print(f"      Std:  {y.std(axis=0)}")
    
    # Create metadata dictionary
    metadata = {
        'n_samples': len(common_cids),
        'n_features': X.shape[1],
        'n_targets': y.shape[1],
        'common_cids': common_cids.tolist(),
        'missing_in_brain': sorted(missing_in_brain) if missing_in_brain else [],
        'missing_in_molecular': sorted(missing_in_molecular) if missing_in_molecular else [],
        'x_nans': int(x_nans),
        'y_nans': int(y_nans),
        'x_infs': int(x_infs),
        'y_infs': int(y_infs),
        'feature_names': X_df.columns.tolist(),
        'target_names': y_df.columns.tolist()
    }
    
    print("\n" + "="*80)
    print("ALIGNMENT COMPLETE ✅")
    print("="*80)
    print(f"Ready for training: X ({X.shape[0]} × {X.shape[1]}) → y ({y.shape[0]} × {y.shape[1]})")
    print("="*80 + "\n")
    
    return X, y, common_cids, metadata
