"""
Training Stage - Train models with PyTorch Lightning

Copyright (c) 2025 Tom White
Licensed under the MIT License

🚫 STUDENTS: DO NOT EDIT THIS FILE
Training is configured in configs/training/*.yaml and configs/model/*.yaml

This stage:
- Loads preprocessed data
- Creates PyTorch Lightning model
- Trains with automatic GPU support, early stopping, checkpointing
- Evaluates on test set
- Saves results

Based on: legacy/neural_network_test.py
Improvements: Automatic training loops, GPU support, early stopping, better logging
"""

import torch
import pytorch_lightning as pl
from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint, LearningRateMonitor
from pytorch_lightning.loggers import CSVLogger, TensorBoardLogger
from pathlib import Path
from typing import Optional, Dict, Any
from omegaconf import DictConfig, OmegaConf
import pandas as pd
import numpy as np

from ..models.base_predictor import OdorPredictor
from ..datamodules.olfactory_datamodule import OlfactoryDataModule
from ..utils.metrics import compute_all_metrics


class TrainingStage:
    """
    Training stage coordinator.
    
    Handles:
    - Model initialization
    - Data loading
    - Training with PyTorch Lightning
    - Evaluation
    - Result saving
    """
    
    def __init__(self, config: DictConfig):
        """
        Args:
            config: Full experiment configuration
        """
        self.config = config
        
        # Paths
        self.output_dir = Path(config.paths.output_dir) / config.experiment_name
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Components (initialized in train())
        self.model = None
        self.datamodule = None
        self.trainer = None
        
        print(f"\n🏋️  Training Stage initialized")
        print(f"   Experiment: {config.experiment_name}")
        print(f"   Output dir: {self.output_dir}")
    
    def _create_callbacks(self) -> list:
        """Create PyTorch Lightning callbacks"""
        callbacks = []
        
        # Early stopping
        if self.config.training.early_stopping.enabled:
            early_stop = EarlyStopping(
                monitor=self.config.training.early_stopping.monitor,
                patience=self.config.training.early_stopping.patience,
                mode=self.config.training.early_stopping.mode,
                verbose=True,
            )
            callbacks.append(early_stop)
            print(f"   ✅ Early stopping enabled (patience={self.config.training.early_stopping.patience})")
        
        # Model checkpointing
        if self.config.training.checkpointing.enabled:
            checkpoint = ModelCheckpoint(
                dirpath=self.output_dir / "checkpoints",
                filename="{epoch}-{val_loss:.4f}",
                monitor=self.config.training.checkpointing.monitor,
                mode=self.config.training.checkpointing.mode,
                save_top_k=self.config.training.checkpointing.save_top_k,
                verbose=True,
            )
            callbacks.append(checkpoint)
            print(f"   ✅ Checkpointing enabled (saving top {self.config.training.checkpointing.save_top_k})")
        
        # Learning rate monitor
        lr_monitor = LearningRateMonitor(logging_interval='epoch')
        callbacks.append(lr_monitor)
        
        return callbacks
    
    def _create_loggers(self) -> list:
        """Create PyTorch Lightning loggers"""
        loggers = []
        
        # CSV Logger (always enabled)
        csv_logger = CSVLogger(
            save_dir=self.output_dir,
            name="logs",
        )
        loggers.append(csv_logger)
        
        # TensorBoard Logger (optional)
        if self.config.training.get('use_tensorboard', True):
            tb_logger = TensorBoardLogger(
                save_dir=self.output_dir,
                name="tensorboard",
            )
            loggers.append(tb_logger)
            print(f"   ✅ TensorBoard logging enabled")
        
        return loggers
    
    def train(self) -> Dict[str, Any]:
        """
        Train the model.
        
        Returns:
            Dictionary with training results and metrics
        """
        print(f"\n{'='*60}")
        print(f"🚀 Starting Training")
        print(f"{'='*60}")
        
        # Create data module
        print(f"\n📊 Setting up data...")
        self.datamodule = OlfactoryDataModule(self.config)
        self.datamodule.setup('fit')
        
        data_info = self.datamodule.get_data_info()
        print(f"   Input dim: {data_info['input_dim']}")
        print(f"   Output dim: {data_info['output_dim']}")
        print(f"   Train size: {data_info['train_size']}")
        print(f"   Val size: {data_info['val_size']}")
        print(f"   Test size: {data_info['test_size']}")
        
        # Update config with data dimensions (temporarily disable struct mode)
        OmegaConf.set_struct(self.config, False)
        self.config.model.input_dim = data_info['input_dim']
        self.config.model.output_dim = data_info['output_dim']
        OmegaConf.set_struct(self.config, True)
        
        # Create model
        print(f"\n🧠 Creating model...")
        self.model = OdorPredictor(self.config)
        
        # Get model summary
        total_params = sum(p.numel() for p in self.model.parameters())
        trainable_params = sum(p.numel() for p in self.model.parameters() if p.requires_grad)
        print(f"   Total parameters: {total_params:,}")
        print(f"   Trainable parameters: {trainable_params:,}")
        
        # Create callbacks and loggers
        callbacks = self._create_callbacks()
        loggers = self._create_loggers()
        
        # Create trainer
        print(f"\n⚙️  Setting up trainer...")
        
        # Determine accelerator
        if torch.cuda.is_available() and self.config.training.get('use_gpu', True):
            accelerator = 'gpu'
            devices = 1
            print(f"   ✅ GPU available: {torch.cuda.get_device_name(0)}")
        elif torch.backends.mps.is_available() and self.config.training.get('use_gpu', True):
            accelerator = 'mps'
            devices = 1
            print(f"   ✅ MPS (Apple Silicon) available")
        else:
            accelerator = 'cpu'
            devices = 1
            print(f"   ℹ️  Using CPU")
        
        self.trainer = pl.Trainer(
            max_epochs=self.config.training.max_epochs,
            accelerator=accelerator,
            devices=devices,
            callbacks=callbacks,
            logger=loggers,
            enable_progress_bar=True,
            enable_model_summary=False,  # We print our own summary
            deterministic=True,
            # Mixed precision (only on GPU)
            precision=self.config.training.get('precision', 32) if accelerator in ['gpu', 'mps'] else 32,
        )
        
        # Train!
        print(f"\n{'='*60}")
        print(f"🏋️  Training model...")
        print(f"{'='*60}\n")
        
        self.trainer.fit(self.model, self.datamodule)
        
        # Evaluate on test set
        print(f"\n{'='*60}")
        print(f"📊 Evaluating on test set...")
        print(f"{'='*60}\n")
        
        test_results = self.trainer.test(self.model, self.datamodule)
        
        # Get best metrics from training
        best_val_loss = self.trainer.callback_metrics.get('val_loss', None)
        # Harmonize metric naming with model logger
        best_val_corr = self.trainer.callback_metrics.get('val_correlation', None)
        
        # Compile results
        results = {
            'experiment_name': self.config.experiment_name,
            'model_config': self.config.model,
            'training_config': self.config.training,
            'data_info': data_info,
            'best_val_loss': float(best_val_loss) if best_val_loss is not None else None,
            'best_val_corr': float(best_val_corr) if best_val_corr is not None else None,
            'test_results': test_results[0] if test_results else None,
            'total_epochs': self.trainer.current_epoch + 1,
            'output_dir': str(self.output_dir),
        }
        
        # Print summary
        self._print_results_summary(results)
        
        # Save results
        self._save_results(results)
        
        return results
    
    def _print_results_summary(self, results: Dict[str, Any]):
        """Print formatted results summary"""
        print(f"\n{'='*60}")
        print(f"✅ Training Complete!")
        print(f"{'='*60}")
        
        print(f"\n📈 Training Summary:")
        print(f"   Total epochs: {results['total_epochs']}")
        
        if results['best_val_loss'] is not None:
            print(f"   Best val loss: {results['best_val_loss']:.4f}")
        
        if results['best_val_corr'] is not None:
            print(f"   Best val correlation: {results['best_val_corr']:.4f}")
        
        if results['test_results']:
            print(f"\n🎯 Test Set Performance:")
            for key, value in results['test_results'].items():
                if isinstance(value, (int, float)):
                    print(f"   {key}: {value:.4f}")
        
        print(f"\n💾 Outputs saved to: {results['output_dir']}")
        print(f"{'='*60}\n")
    
    def _save_results(self, results: Dict[str, Any]):
        """Save results to disk"""
        # Save metrics as CSV
        metrics_df = pd.DataFrame([{
            'experiment': results['experiment_name'],
            'val_loss': results['best_val_loss'],
            'val_corr': results['best_val_corr'],
            **results['test_results']
        }])
        
        metrics_path = self.output_dir / "metrics.csv"
        metrics_df.to_csv(metrics_path, index=False)
        print(f"   Saved metrics: {metrics_path}")
        
        # Save config
        config_path = self.output_dir / "config.yaml"
        with open(config_path, 'w') as f:
            from omegaconf import OmegaConf
            OmegaConf.save(self.config, f)
        print(f"   Saved config: {config_path}")


def train_model(config: DictConfig) -> Dict[str, Any]:
    """
    Main function to train a model.
    
    Args:
        config: Full experiment configuration
    
    Returns:
        Dictionary with training results
    """
    stage = TrainingStage(config)
    results = stage.train()
    return results
