"""
Base Predictor Model - PyTorch Lightning Module

Copyright (c) 2025 Tom White
Licensed under the MIT License

🚫 STUDENTS: DO NOT EDIT THIS FILE
This is core infrastructure. To configure the model, edit your
experiment config file in configs/experiment/

This module provides a universal model that can be configured entirely
through YAML files. It handles:
- Model architecture building
- Training/validation loops
- Optimization
- Logging
- All PyTorch Lightning features (checkpointing, early stopping, etc.)
"""

import torch
import torch.nn as nn
import pytorch_lightning as pl
from typing import Dict, List, Any
from omegaconf import DictConfig


class OdorPredictor(pl.LightningModule):
    """
    Universal predictor model configured via config files.
    
    This model can handle different architectures just by changing config.
    No code changes needed for experiments!
    """
    
    def __init__(self, config: DictConfig):
        super().__init__()
        
        # Save hyperparameters for logging
        self.save_hyperparameters()
        
        # Store config
        self.config = config
        
        # Build model architecture from config
        self.model = self._build_architecture()
        
        # Loss function from config
        self.criterion = self._get_loss_function()
        
        # For tracking best validation metrics
        self.validation_step_outputs = []
        
    def _build_architecture(self) -> nn.Module:
        """
        Build neural network architecture from config.
        
        Reads config.model.architecture and builds the network.
        Example config:
            hidden_layers: [128, 64, 32]
            activation: relu
            dropout: 0.3
        """
        arch_config = self.config.model.architecture
        
        # Get input/output dimensions from config (set by datamodule)
        input_dim = self.config.data.get('input_dim', None)
        output_dim = self.config.data.get('output_dim', 1)
        
        if input_dim is None:
            # Will be set later by datamodule
            input_dim = 100  # Placeholder
        
        # Build sequential layers
        layers = []
        hidden_layers = arch_config.hidden_layers
        
        # Input layer
        prev_size = input_dim
        for hidden_size in hidden_layers:
            # Linear layer
            layers.append(nn.Linear(prev_size, hidden_size))
            
            # Batch normalization (optional)
            if arch_config.get('batch_norm', False):
                layers.append(nn.BatchNorm1d(hidden_size))
            
            # Activation
            activation = arch_config.get('activation', 'relu').lower()
            if activation == 'relu':
                layers.append(nn.ReLU())
            elif activation == 'leaky_relu':
                layers.append(nn.LeakyReLU())
            elif activation == 'tanh':
                layers.append(nn.Tanh())
            elif activation == 'sigmoid':
                layers.append(nn.Sigmoid())
            
            # Dropout
            dropout = arch_config.get('dropout', 0.0)
            if dropout > 0:
                layers.append(nn.Dropout(dropout))
            
            prev_size = hidden_size
        
        # Output layer (no activation)
        layers.append(nn.Linear(prev_size, output_dim))
        
        return nn.Sequential(*layers)
    
    def _get_loss_function(self) -> nn.Module:
        """Get loss function from config"""
        loss_name = self.config.model.get('loss', 'mse').lower()
        
        if loss_name == 'mse':
            return nn.MSELoss()
        elif loss_name == 'mae' or loss_name == 'l1':
            return nn.L1Loss()
        elif loss_name == 'huber':
            return nn.HuberLoss()
        else:
            raise ValueError(f"Unknown loss function: {loss_name}")
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass through the model"""
        return self.model(x)
    
    def training_step(self, batch: tuple, batch_idx: int) -> torch.Tensor:
        """
        Training step - called automatically by PyTorch Lightning.
        
        Args:
            batch: (x, y) tuple from dataloader
            batch_idx: Index of batch
            
        Returns:
            loss: Training loss
        """
        x, y = batch
        
        # Forward pass
        y_hat = self(x)
        
        # Compute loss
        loss = self.criterion(y_hat, y)
        
        # Log metrics (automatically sent to TensorBoard)
        self.log('train_loss', loss, on_step=False, on_epoch=True, prog_bar=True)
        
        return loss
    
    def validation_step(self, batch: tuple, batch_idx: int) -> Dict[str, torch.Tensor]:
        """
        Validation step - called automatically by PyTorch Lightning.
        
        Args:
            batch: (x, y) tuple from dataloader
            batch_idx: Index of batch
            
        Returns:
            dict: Dictionary of metrics
        """
        x, y = batch
        
        # Forward pass
        y_hat = self(x)
        
        # Compute loss
        loss = self.criterion(y_hat, y)
        
        # Compute correlation (overall Pearson across all targets)
        correlation = self._compute_correlation(y_hat, y)
        # If multi-output, also log per-target correlations
        if y_hat.ndim == 2 and y_hat.shape[1] > 1:
            per_corr = self._compute_per_target_correlation(y_hat, y)
            for i, c in enumerate(per_corr):
                self.log(f'val_corr_PC{i+1}', c, on_step=False, on_epoch=True, prog_bar=False)
        
        # Log metrics
        self.log('val_loss', loss, on_step=False, on_epoch=True, prog_bar=True)
        self.log('val_correlation', correlation, on_step=False, on_epoch=True, prog_bar=True)
        
        # Store for epoch-level metrics
        self.validation_step_outputs.append({
            'val_loss': loss,
            'val_correlation': correlation,
            'y_hat': y_hat.detach(),
            'y': y.detach()
        })
        
        return {'val_loss': loss, 'val_correlation': correlation}
    
    def on_validation_epoch_end(self):
        """Called at the end of validation epoch"""
        if not self.validation_step_outputs:
            return
        
        # Aggregate predictions across all batches
        all_y_hat = torch.cat([x['y_hat'] for x in self.validation_step_outputs])
        all_y = torch.cat([x['y'] for x in self.validation_step_outputs])
        
        # Compute epoch-level correlation
        epoch_correlation = self._compute_correlation(all_y_hat, all_y)
        
        self.log('val_correlation_epoch', epoch_correlation, prog_bar=False)
        
        # Clear for next epoch
        self.validation_step_outputs.clear()
    
    def test_step(self, batch: tuple, batch_idx: int) -> Dict[str, torch.Tensor]:
        """
        Test step - called automatically by PyTorch Lightning.
        Same as validation but with test data.
        """
        x, y = batch
        y_hat = self(x)
        loss = self.criterion(y_hat, y)
        correlation = self._compute_correlation(y_hat, y)
        if y_hat.ndim == 2 and y_hat.shape[1] > 1:
            per_corr = self._compute_per_target_correlation(y_hat, y)
            for i, c in enumerate(per_corr):
                self.log(f'test_corr_PC{i+1}', c, on_step=False, on_epoch=True)
        
        self.log('test_loss', loss, on_step=False, on_epoch=True)
        self.log('test_correlation', correlation, on_step=False, on_epoch=True)
        
        return {'test_loss': loss, 'test_correlation': correlation}
    
    def _compute_correlation(self, pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        """
        Compute Pearson correlation between predictions and targets.
        
        This is your key metric for brain activation prediction!
        
        Args:
            pred: Predictions [batch_size, features]
            target: Ground truth [batch_size, features]
            
        Returns:
            correlation: Pearson correlation coefficient
        """
        # Flatten tensors
        pred_flat = pred.view(-1)
        target_flat = target.view(-1)
        
        # Compute means
        pred_mean = pred_flat.mean()
        target_mean = target_flat.mean()
        
        # Compute covariance
        covariance = ((pred_flat - pred_mean) * (target_flat - target_mean)).mean()
        
        # Compute standard deviations
        pred_std = pred_flat.std()
        target_std = target_flat.std()
        
        # Compute correlation (add small epsilon for numerical stability)
        correlation = covariance / (pred_std * target_std + 1e-8)
        
        return correlation

    def _compute_per_target_correlation(self, pred: torch.Tensor, target: torch.Tensor):
        """Compute Pearson correlation per target dimension for multi-output."""
        if pred.ndim == 1:
            return [self._compute_correlation(pred, target)]
        corrs = []
        for j in range(pred.shape[1]):
            corrs.append(self._compute_correlation(pred[:, j], target[:, j]))
        return corrs
    
    def configure_optimizers(self) -> Dict[str, Any]:
        """
        Configure optimizer from config.
        
        Called automatically by PyTorch Lightning.
        
        Returns:
            dict: Optimizer configuration
        """
        opt_config = self.config.model.optimizer
        
        # Get optimizer type
        opt_type = opt_config.get('type', 'adam').lower()
        lr = opt_config.get('learning_rate', 0.001)
        weight_decay = opt_config.get('weight_decay', 0.0)
        
        # Create optimizer
        if opt_type == 'adam':
            optimizer = torch.optim.Adam(
                self.parameters(),
                lr=lr,
                weight_decay=weight_decay
            )
        elif opt_type == 'adamw':
            optimizer = torch.optim.AdamW(
                self.parameters(),
                lr=lr,
                weight_decay=weight_decay
            )
        elif opt_type == 'sgd':
            momentum = opt_config.get('momentum', 0.9)
            optimizer = torch.optim.SGD(
                self.parameters(),
                lr=lr,
                momentum=momentum,
                weight_decay=weight_decay
            )
        else:
            raise ValueError(f"Unknown optimizer: {opt_type}")
        
        # Optional: Learning rate scheduler
        if self.config.model.get('scheduler', None):
            scheduler_config = self.config.model.scheduler
            scheduler_type = scheduler_config.get('type', 'reduce_on_plateau')
            
            if scheduler_type == 'reduce_on_plateau':
                scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                    optimizer,
                    mode='min',
                    factor=scheduler_config.get('factor', 0.5),
                    patience=scheduler_config.get('patience', 10),
                    verbose=True
                )
                return {
                    'optimizer': optimizer,
                    'lr_scheduler': {
                        'scheduler': scheduler,
                        'monitor': 'val_loss',
                    }
                }
        
        return optimizer
    
    def get_model_summary(self) -> str:
        """Get a summary of the model architecture"""
        total_params = sum(p.numel() for p in self.parameters())
        trainable_params = sum(p.numel() for p in self.parameters() if p.requires_grad)
        
        summary = f"""
Model Architecture Summary:
--------------------------
Type: {self.config.model.get('type', 'feedforward')}
Hidden Layers: {self.config.model.architecture.hidden_layers}
Activation: {self.config.model.architecture.get('activation', 'relu')}
Dropout: {self.config.model.architecture.get('dropout', 0.0)}
Batch Norm: {self.config.model.architecture.get('batch_norm', False)}

Parameters:
--------------------------
Total: {total_params:,}
Trainable: {trainable_params:,}

Optimizer: {self.config.model.optimizer.get('type', 'adam')}
Learning Rate: {self.config.model.optimizer.get('learning_rate', 0.001)}
Loss: {self.config.model.get('loss', 'mse')}
"""
        return summary
